---
Name: dashboard_welcome_quicklinks
After:
  - '#cmsdefaultadmin'
---
SilverStripe\Admin\AdminRootController:
  default_panel: Sunnysideup\DashboardWelcomeQuicklinks\Admin\DashboardWelcomeQuickLinks
